name: Bundle Maven CI

on: [workflow_dispatch, workflow_call, push, pull_request]

jobs:
  call-workflow:
    uses: Forsakringskassan/.github/.github/workflows/bundle-maven-ci.yaml@ab3bb83e2b18cfda27046b399b61780fa888b524
    secrets:
      PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
      PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}