name: Bundle Maven Release

on: [workflow_dispatch]

jobs:
  call-workflow:
    uses: Forsakringskassan/.github/.github/workflows/bundle-maven-release.yaml@244fcf3a37f7910c4041498c146cb1b9efb1ee95
    secrets:
      PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
      PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}